#!/bin/bash

# 🎯 SOLUÇÕES PARA CRIAR DNS grafana.leoproti.com.br

echo "🚨 O comando cloudflared tunnel route dns falha porque precisa de certificado de origem."
echo ""
echo "📋 SOLUÇÃO 1 - API Cloudflare (Recomendada):"
echo ""
echo "1️⃣ Obter API Token:"
echo "   - Acesse: https://dash.cloudflare.com/profile/api-tokens"
echo "   - Create Token → Custom token"
echo "   - Permissions: Zone:DNS:Edit"
echo "   - Zone Resources: Include → leoproti.com.br"
echo ""
echo "2️⃣ Obter Zone ID:"
echo "   curl -X GET \"https://api.cloudflare.com/client/v4/zones\" \\"
echo "        -H \"Authorization: Bearer SEU_API_TOKEN\" | \\"
echo "        jq '.result[] | select(.name==\"leoproti.com.br\") | .id'"
echo ""
echo "3️⃣ Criar DNS Record:"
echo "   curl -X POST \"https://api.cloudflare.com/client/v4/zones/ZONE_ID/dns_records\" \\"
echo "        -H \"Authorization: Bearer SEU_API_TOKEN\" \\"
echo "        -H \"Content-Type: application/json\" \\"
echo "        --data '{"
echo "          \"type\": \"CNAME\","
echo "          \"name\": \"grafana\","
echo "          \"content\": \"7637938c-e1ee-4090-af2f-5769aa7aa580.cfargotunnel.com\","
echo "          \"proxied\": true"
echo "        }'"
echo ""
echo "📋 SOLUÇÃO 2 - Painel Web (Mais fácil):"
echo ""
echo "1️⃣ Acesse: https://dash.cloudflare.com"
echo "2️⃣ Selecione: leoproti.com.br"
echo "3️⃣ DNS → Records → Add record"
echo "4️⃣ Configure:"
echo "   Type: CNAME"
echo "   Name: grafana"
echo "   Content: 7637938c-e1ee-4090-af2f-5769aa7aa580.cfargotunnel.com"
echo "   Proxy: ✅ ATIVADO"
echo "5️⃣ Save"
echo ""
echo "🎯 Resultado: https://grafana.leoproti.com.br"
echo "⏱️ Tempo: 1-5 minutos para propagar"
echo ""
echo "✅ Configuração do Cloudflared já está pronta!"
echo "✅ Grafana rodando em localhost:3000"
echo "🔐 Login: admin / CloudflaredGrafana2025"